services:
    php:
        container_name: php
        build:
            context: ./config/php
        ports:
            - 9000:9000
        volumes:
            - ./www:/srv/www
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - db
        links:
            - db
 
    nginx:
        container_name: nginx
        image: nginx:1.25.5
        ports:
            - 80:80
        volumes:
            - ./www:/srv/www
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    pma:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            UPLOAD_LIMIT: 1073741824
            restart: always
        ports:
            - ${IP}:8000:80
        links:
            - db

    db:
        container_name: db
        image: mysql:latest
        restart: always
        ports:
            - ${IP}:3300:3306
        command: "mysqld --init-file /data/application/init.sql"
        volumes:
            - ./data/init.sql:/data/application/init.sql
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: MySQL
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

volumes:
    db_data:
